### ISSUE TITLE
Getting error when trying to compile

### ISSUE THREAD

**Issue by indysingh11** [manu-mannattil/vachart#1]
Hi! 

I've just trying compiling your program, but am getting the error: 

```
! I can't find file `"|python3 snellen.py --defs"'.
<argument> ...@input "|python3 snellen.py --defs"

l.27 \input{|python3 snellen.py --defs}

(Press Enter to retry, or Control-Z to exit)
Please type another input file name:
```

I don't have a huge amount of programming experience, and no Tex experience at all. I've spent the last few hours trying to fix it, but I'm not having any luck. I assume I'm probably doing something simple wrong due to the lack of experience haha.

Do you have any advice? I'm on Windows, I downloaded TexWorks, tried running the Snellen.tex file in TexWorks using XeLaTeX, and I've also tried compiling via Tex Live, getting the same error message above.

Would be awesome if you could help as what you have created is exactly what I'd like. 
Thanks!
Indy

**Comment by manu-mannattil** [comment]
Unfortunately, I don't have much experience with Windows to test this.  I also don't use a LaTeX editor like TeXWorks, so I couldn't reproduce the error message exactly.  But I have some thoughts,

-  Do you have Python installed on your system?  Can you run `python3` on the Windows command-line shell?

-  Are you compiling the file using `xelatex --shell-escape`?  Without this, the required output of the external script `snellen.py` will not be included. See [here](https://tex.stackexchange.com/questions/82699/how-to-enable-shell-escape-in-texworks) for a Q&A on enabling `--shell-escape` with TeXWorks.

-  I don't know much about the Windows command-line shell, and perhaps this isn't the right way to do things, but can you try running `xelatex --shell-escape snellen.tex` if you can't get TeXWorks to compile the document?

-  As a final alternative, if you can run the `snellen.py` script using Python, just replace the `\input{|python3 snellen.py 10}` line in `snellen.tex` with the script's output.

I would've suggested [Overleaf](https://www.overleaf.com) as an alternative to installing LaTeX on your computer, but we need to be able to run the script `snellen.py` and AFAIK Overleaf doesn't support running external commands.

**Comment by indysingh11** [comment]
I've managed to get it to work! Thank you so much.
I'd installed Python 3.12 online, but it was only when I installed Python throught the CMD (which downloaded Python 3.11, not that I imagine that version change matters) did it work. I also had to follow your seocnd bullet point.
Thanks for the detailed response and for allowing use of this project :)
